[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    "setup.py",
    "build",
    "dist",
    "releases",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".vscode",
    ".github",
]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes errors
    "W",  # pycodestyle warnings
    "C",  # mccabe complexity checker
    "B",  # bugbear best practices checker
    "T",  # mypy type errors
    "B", # flake8-bugbear best practices checker
    "I001", # isort import order
]
ignore = [      # TODO: to be removed
    "C401",  # Unnecessary generator (rewrite as a `set` comprehension)
    "C405",  # Unnecessary list literal - rewrite as a literal
    "C408",  # Unnecessary dict call - rewrite as a literal
    "C409",  # Unnecessary list passed to tuple() - rewrite as a tuple literal
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]  # unused import
"_init.py" = ["F401", "F403"]  # unused import
"taipy/config/stubs/pyi_header.py" = ["F401", "F403"]  # unused import
"taipy/templates/*" = ["F401", "F403", "T201"]  # unused import, `print` found

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
ignore_missing_imports = true
implicit_optional = true
namespace_packages = false
exclude = "(taipy/templates/|generate_pyi.py|tools)"
follow_imports = "skip"

[tool.pyright]

[tool.codespell]
skip = '.git,*.pdf,*.svg,go.sum,package-lock.json,*.css'
check-hidden = true
ignore-regex = '^\s*"image/\S+": ".*|\b(inPort|anId|IST|Opps|Rouge|notifAction)\b'
# some unfortunate names for variables
ignore-words-list = 'ags,selt'
