name: Test package installation

on:
  push:
    branches: [ develop, dev/*, release/* ]
  pull_request:
    branches: [ develop, dev/*, release/* ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  standard-packages:
    timeout-minutes: 10
    strategy:
      matrix:
        python-versions: [ '3.8', '3.9', '3.10', '3.11' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Test packaging
        run: |
          pip install .
          python -c "import taipy as tp; tp.Scenario"

  optionals-packages:
    timeout-minutes: 10
    strategy:
      matrix:
        python-versions: [ '3.8', '3.9', '3.10', '3.11' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Test packaging with optional package
        run: |
          # Extract optionals packages before installing them
          grep -n 'setup(' setup.py | cut -d ":" -f 1 | xargs -I% bash -c "expr % - 1" | xargs -I% bash -c 'head -n% setup.py' > setup_packages.py
          echo "[print(k) for k in extras_require.keys()]" >> setup_packages.py
          python setup_packages.py | xargs -I% bash -c "pip install .[%]"

          python -c "import taipy as tp; tp.Scenario"
