name: Benchmark on taipy-integration-testing
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger taipy-integration-testing
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.TAIPY_INTEGRATION_TESTING_ACCESS_TOKEN}}
          repository: avaiga/taipy-integration-testing
          event-type: benchmark
          client-payload: '{"repo": "taipy-core", "commitSHA": "${{ github.sha }}"}'
