name: 'code-coverage'
on:
  pull_request:
    branches: [ master,main,release ]
  workflow_dispatch:

jobs:
  backend-code-coverage:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Lint and Coverage
        run: |
          sed 's/ssh/https/g' Pipfile > Pipfile.copy
          sed 's/git@github/${{ secrets.PERSONAL_TOKEN }}@github/g' Pipfile.copy > Pipfile

          pip install tox
          tox

      - name: Code coverage
        uses: orgoro/coverage@v2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
