name: Trigger Doc
on:
  push:
    branches: [ develop ]
jobs:
  trigger:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Trigger taipy-doc build on develop branch push
        run: gh workflow run doc.yml -f user-to-notify=$GITHUB_ACTOR -R Avaiga/taipy-doc
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_OTHER_ACTION }}
