name: Setuptools

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  standard-packages:
    timeout-minutes: 10
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Taipy without dependencies
        run: |
          pip install .
          rm -r taipy gui  # Removal of Taipy code to ensure the use of the installed package

          pip install pytest pytest-mock
          pytest

